/** Generated by scripts/generate-valid-routes.mjs — do not edit manually */
export const VALID_ROUTES = new Set([
  "/",
  "/about",
  "/products",
  "/factory",
  "/certifications",
  "/oem",
  "/markets",
  "/applications",
  "/faq",
  "/contact",
  "/blog",
  "/privacy",
  "/terms",
  "/products/acetylene-cylinders",
  "/products/propane-cylinders",
  "/products/lpg-cylinders",
  "/products/industrial-gas-cylinders",
  "/products/generators",
  "/products/welding-accessories",
  "/products/refrigeration"
])
